# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, -7, 711, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonD3h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD3h.setText("")
        self.buttonD3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD3h.setObjectName("buttonD3h")
        self.gridLayout_2.addWidget(self.buttonD3h, 7, 8, 1, 1)
        self.buttonF5v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonF5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF5v.setText("")
        self.buttonF5v.setObjectName("buttonF5v")
        self.gridLayout_2.addWidget(self.buttonF5v, 2, 11, 1, 1)
        self.buttonC5h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC5h.setText("")
        self.buttonC5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC5h.setObjectName("buttonC5h")
        self.gridLayout_2.addWidget(self.buttonC5h, 3, 6, 1, 1)
        self.columnView_5 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_5.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_5.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_5.setObjectName("columnView_5")
        self.gridLayout_2.addWidget(self.columnView_5, 2, 10, 1, 1)
        self.buttonE5v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE5v.setText("")
        self.buttonE5v.setObjectName("buttonE5v")
        self.gridLayout_2.addWidget(self.buttonE5v, 2, 9, 1, 1)
        self.buttonD4h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD4h.setText("")
        self.buttonD4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD4h.setObjectName("buttonD4h")
        self.gridLayout_2.addWidget(self.buttonD4h, 5, 8, 1, 1)
        self.buttonD3v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD3v.setText("")
        self.buttonD3v.setObjectName("buttonD3v")
        self.gridLayout_2.addWidget(self.buttonD3v, 6, 7, 1, 1)
        self.buttonD5v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD5v.setText("")
        self.buttonD5v.setObjectName("buttonD5v")
        self.gridLayout_2.addWidget(self.buttonD5v, 2, 7, 1, 1)
        self.buttonB4v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB4v.setText("")
        self.buttonB4v.setObjectName("buttonB4v")
        self.gridLayout_2.addWidget(self.buttonB4v, 4, 3, 1, 1)
        self.buttonD1h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD1h.setText("")
        self.buttonD1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD1h.setObjectName("buttonD1h")
        self.gridLayout_2.addWidget(self.buttonD1h, 11, 8, 1, 1)
        self.columnView_16 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_16.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_16.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_16.setObjectName("columnView_16")
        self.gridLayout_2.addWidget(self.columnView_16, 8, 8, 1, 1)
        self.columnView_19 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_19.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_19.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_19.setObjectName("columnView_19")
        self.gridLayout_2.addWidget(self.columnView_19, 4, 8, 1, 1)
        self.columnView_2 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_2.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_2.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_2.setObjectName("columnView_2")
        self.gridLayout_2.addWidget(self.columnView_2, 2, 4, 1, 1)
        self.buttonD4v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD4v.setText("")
        self.buttonD4v.setObjectName("buttonD4v")
        self.gridLayout_2.addWidget(self.buttonD4v, 4, 7, 1, 1)
        self.buttonB2v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB2v.setText("")
        self.buttonB2v.setObjectName("buttonB2v")
        self.gridLayout_2.addWidget(self.buttonB2v, 8, 3, 1, 1)
        self.buttonE2h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE2h.setText("")
        self.buttonE2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE2h.setObjectName("buttonE2h")
        self.gridLayout_2.addWidget(self.buttonE2h, 9, 10, 1, 1)
        self.buttonE6h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE6h.setText("")
        self.buttonE6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE6h.setObjectName("buttonE6h")
        self.gridLayout_2.addWidget(self.buttonE6h, 1, 10, 1, 1)
        self.buttonC1h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC1h.setText("")
        self.buttonC1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC1h.setObjectName("buttonC1h")
        self.gridLayout_2.addWidget(self.buttonC1h, 11, 6, 1, 1)
        self.columnView_24 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_24.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_24.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_24.setObjectName("columnView_24")
        self.gridLayout_2.addWidget(self.columnView_24, 10, 10, 1, 1)
        self.buttonB2h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB2h.setText("")
        self.buttonB2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB2h.setObjectName("buttonB2h")
        self.gridLayout_2.addWidget(self.buttonB2h, 9, 4, 1, 1)
        self.columnView_25 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_25.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_25.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_25.setObjectName("columnView_25")
        self.gridLayout_2.addWidget(self.columnView_25, 10, 8, 1, 1)
        self.columnView_18 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_18.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_18.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_18.setObjectName("columnView_18")
        self.gridLayout_2.addWidget(self.columnView_18, 4, 6, 1, 1)
        self.columnView_9 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_9.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_9.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_9.setObjectName("columnView_9")
        self.gridLayout_2.addWidget(self.columnView_9, 10, 2, 1, 1)
        self.buttonA1v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA1v.setText("")
        self.buttonA1v.setObjectName("buttonA1v")
        self.gridLayout_2.addWidget(self.buttonA1v, 10, 1, 1, 1)
        self.buttonA4v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA4v.setText("")
        self.buttonA4v.setObjectName("buttonA4v")
        self.gridLayout_2.addWidget(self.buttonA4v, 4, 1, 1, 1)
        self.buttonB1h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB1h.setText("")
        self.buttonB1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB1h.setObjectName("buttonB1h")
        self.gridLayout_2.addWidget(self.buttonB1h, 11, 4, 1, 1)
        self.columnView_6 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_6.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_6.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_6.setObjectName("columnView_6")
        self.gridLayout_2.addWidget(self.columnView_6, 4, 2, 1, 1)
        self.buttonC5v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC5v.setText("")
        self.buttonC5v.setObjectName("buttonC5v")
        self.gridLayout_2.addWidget(self.buttonC5v, 2, 5, 1, 1)
        self.buttonF2v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonF2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF2v.setText("")
        self.buttonF2v.setObjectName("buttonF2v")
        self.gridLayout_2.addWidget(self.buttonF2v, 8, 11, 1, 1)
        self.columnView_14 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_14.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_14.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_14.setObjectName("columnView_14")
        self.gridLayout_2.addWidget(self.columnView_14, 10, 6, 1, 1)
        self.buttonD5h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD5h.setText("")
        self.buttonD5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD5h.setObjectName("buttonD5h")
        self.gridLayout_2.addWidget(self.buttonD5h, 3, 8, 1, 1)
        self.buttonD2v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD2v.setText("")
        self.buttonD2v.setObjectName("buttonD2v")
        self.gridLayout_2.addWidget(self.buttonD2v, 8, 7, 1, 1)
        self.buttonC2h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC2h.setText("")
        self.buttonC2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC2h.setObjectName("buttonC2h")
        self.gridLayout_2.addWidget(self.buttonC2h, 9, 6, 1, 1)
        self.columnView = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView.setObjectName("columnView")
        self.gridLayout_2.addWidget(self.columnView, 2, 2, 1, 1)
        self.buttonC3h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC3h.setText("")
        self.buttonC3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC3h.setObjectName("buttonC3h")
        self.gridLayout_2.addWidget(self.buttonC3h, 7, 6, 1, 1)
        self.buttonD1v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonD1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonD1v.setText("")
        self.buttonD1v.setObjectName("buttonD1v")
        self.gridLayout_2.addWidget(self.buttonD1v, 10, 7, 1, 1)
        self.label6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label6.setObjectName("label6")
        self.gridLayout_2.addWidget(self.label6, 0, 0, 2, 1)
        self.buttonE5h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE5h.setText("")
        self.buttonE5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE5h.setObjectName("buttonE5h")
        self.gridLayout_2.addWidget(self.buttonE5h, 3, 10, 1, 1)
        self.buttonF1v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonF1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF1v.setText("")
        self.buttonF1v.setObjectName("buttonF1v")
        self.gridLayout_2.addWidget(self.buttonF1v, 10, 11, 1, 1)
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 10, 0, 2, 1)
        self.buttonB3h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB3h.setText("")
        self.buttonB3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB3h.setObjectName("buttonB3h")
        self.gridLayout_2.addWidget(self.buttonB3h, 7, 4, 1, 1)
        self.columnView_15 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_15.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_15.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_15.setObjectName("columnView_15")
        self.gridLayout_2.addWidget(self.columnView_15, 8, 6, 1, 1)
        self.labelD = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelD.setFont(font)
        self.labelD.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelD.setObjectName("labelD")
        self.gridLayout_2.addWidget(self.labelD, 12, 7, 1, 2)
        self.columnView_4 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_4.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_4.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_4.setObjectName("columnView_4")
        self.gridLayout_2.addWidget(self.columnView_4, 2, 8, 1, 1)
        self.buttonC4v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC4v.setText("")
        self.buttonC4v.setObjectName("buttonC4v")
        self.gridLayout_2.addWidget(self.buttonC4v, 4, 5, 1, 1)
        self.buttonD6h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD6h.setText("")
        self.buttonD6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD6h.setObjectName("buttonD6h")
        self.gridLayout_2.addWidget(self.buttonD6h, 1, 8, 1, 1)
        self.buttonE2v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE2v.setText("")
        self.buttonE2v.setObjectName("buttonE2v")
        self.gridLayout_2.addWidget(self.buttonE2v, 8, 9, 1, 1)
        self.columnView_20 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_20.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_20.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_20.setObjectName("columnView_20")
        self.gridLayout_2.addWidget(self.columnView_20, 6, 8, 1, 1)
        self.columnView_17 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_17.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_17.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_17.setObjectName("columnView_17")
        self.gridLayout_2.addWidget(self.columnView_17, 6, 6, 1, 1)
        self.buttonA4h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA4h.setText("")
        self.buttonA4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA4h.setObjectName("buttonA4h")
        self.gridLayout_2.addWidget(self.buttonA4h, 5, 2, 1, 1)
        self.buttonE4v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE4v.setText("")
        self.buttonE4v.setObjectName("buttonE4v")
        self.gridLayout_2.addWidget(self.buttonE4v, 4, 9, 1, 1)
        self.labelA = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelA.setFont(font)
        self.labelA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelA.setObjectName("labelA")
        self.gridLayout_2.addWidget(self.labelA, 12, 1, 1, 2)
        self.buttonA2h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA2h.setText("")
        self.buttonA2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA2h.setObjectName("buttonA2h")
        self.gridLayout_2.addWidget(self.buttonA2h, 9, 2, 1, 1)
        self.buttonC3v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC3v.setText("")
        self.buttonC3v.setObjectName("buttonC3v")
        self.gridLayout_2.addWidget(self.buttonC3v, 6, 5, 1, 1)
        self.buttonA3v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA3v.setText("")
        self.buttonA3v.setObjectName("buttonA3v")
        self.gridLayout_2.addWidget(self.buttonA3v, 6, 1, 1, 1)
        self.buttonA6h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA6h.setText("")
        self.buttonA6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA6h.setObjectName("buttonA6h")
        self.gridLayout_2.addWidget(self.buttonA6h, 1, 2, 1, 1)
        self.columnView_3 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_3.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_3.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_3.setObjectName("columnView_3")
        self.gridLayout_2.addWidget(self.columnView_3, 2, 6, 1, 1)
        self.columnView_8 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_8.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_8.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_8.setObjectName("columnView_8")
        self.gridLayout_2.addWidget(self.columnView_8, 8, 2, 1, 1)
        self.buttonC2v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC2v.setText("")
        self.buttonC2v.setObjectName("buttonC2v")
        self.gridLayout_2.addWidget(self.buttonC2v, 8, 5, 1, 1)
        self.label4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 4, 0, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 12, 11, 1)
        self.buttonE1v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE1v.setText("")
        self.buttonE1v.setObjectName("buttonE1v")
        self.gridLayout_2.addWidget(self.buttonE1v, 10, 9, 1, 1)
        self.buttonF3v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonF3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF3v.setText("")
        self.buttonF3v.setObjectName("buttonF3v")
        self.gridLayout_2.addWidget(self.buttonF3v, 6, 11, 1, 1)
        self.buttonF4v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonF4v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonF4v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonF4v.setText("")
        self.buttonF4v.setObjectName("buttonF4v")
        self.gridLayout_2.addWidget(self.buttonF4v, 4, 11, 1, 1)
        self.buttonC6h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC6h.setText("")
        self.buttonC6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonC6h.setObjectName("buttonC6h")
        self.gridLayout_2.addWidget(self.buttonC6h, 1, 6, 1, 1)
        self.buttonE3h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE3h.setText("")
        self.buttonE3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE3h.setObjectName("buttonE3h")
        self.gridLayout_2.addWidget(self.buttonE3h, 7, 10, 1, 1)
        self.buttonE1h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE1h.setText("")
        self.buttonE1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE1h.setObjectName("buttonE1h")
        self.gridLayout_2.addWidget(self.buttonE1h, 11, 10, 1, 1)
        self.columnView_11 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_11.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_11.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_11.setObjectName("columnView_11")
        self.gridLayout_2.addWidget(self.columnView_11, 6, 4, 1, 1)
        self.columnView_22 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_22.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_22.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_22.setObjectName("columnView_22")
        self.gridLayout_2.addWidget(self.columnView_22, 6, 10, 1, 1)
        self.buttonA5v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA5v.setText("")
        self.buttonA5v.setObjectName("buttonA5v")
        self.gridLayout_2.addWidget(self.buttonA5v, 2, 1, 1, 1)
        self.columnView_13 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_13.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_13.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_13.setObjectName("columnView_13")
        self.gridLayout_2.addWidget(self.columnView_13, 10, 4, 1, 1)
        self.buttonD2h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonD2h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonD2h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonD2h.setText("")
        self.buttonD2h.setIconSize(QtCore.QSize(50, 3))
        self.buttonD2h.setObjectName("buttonD2h")
        self.gridLayout_2.addWidget(self.buttonD2h, 9, 8, 1, 1)
        self.columnView_12 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_12.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_12.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_12.setObjectName("columnView_12")
        self.gridLayout_2.addWidget(self.columnView_12, 8, 4, 1, 1)
        self.buttonA2v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA2v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonA2v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonA2v.setText("")
        self.buttonA2v.setObjectName("buttonA2v")
        self.gridLayout_2.addWidget(self.buttonA2v, 8, 1, 1, 1)
        self.columnView_21 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_21.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_21.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_21.setObjectName("columnView_21")
        self.gridLayout_2.addWidget(self.columnView_21, 4, 10, 1, 1)
        self.buttonA5h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA5h.setText("")
        self.buttonA5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA5h.setObjectName("buttonA5h")
        self.gridLayout_2.addWidget(self.buttonA5h, 3, 2, 1, 1)
        self.columnView_23 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_23.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_23.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_23.setObjectName("columnView_23")
        self.gridLayout_2.addWidget(self.columnView_23, 8, 10, 1, 1)
        self.buttonB5v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB5v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB5v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB5v.setText("")
        self.buttonB5v.setObjectName("buttonB5v")
        self.gridLayout_2.addWidget(self.buttonB5v, 2, 3, 1, 1)
        self.buttonE3v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonE3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonE3v.setText("")
        self.buttonE3v.setObjectName("buttonE3v")
        self.gridLayout_2.addWidget(self.buttonE3v, 6, 9, 1, 1)
        self.columnView_7 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_7.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_7.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_7.setObjectName("columnView_7")
        self.gridLayout_2.addWidget(self.columnView_7, 6, 2, 1, 1)
        self.columnView_10 = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView_10.setMinimumSize(QtCore.QSize(80, 80))
        self.columnView_10.setMaximumSize(QtCore.QSize(80, 80))
        self.columnView_10.setObjectName("columnView_10")
        self.gridLayout_2.addWidget(self.columnView_10, 4, 4, 1, 1)
        self.label3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 6, 0, 2, 1)
        self.buttonA3h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA3h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA3h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA3h.setText("")
        self.buttonA3h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA3h.setObjectName("buttonA3h")
        self.gridLayout_2.addWidget(self.buttonA3h, 7, 2, 1, 1)
        self.labelC = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelC.setFont(font)
        self.labelC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelC.setObjectName("labelC")
        self.gridLayout_2.addWidget(self.labelC, 12, 5, 1, 2)
        self.buttonC1v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonC1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonC1v.setText("")
        self.buttonC1v.setObjectName("buttonC1v")
        self.gridLayout_2.addWidget(self.buttonC1v, 10, 5, 1, 1)
        self.buttonA1h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonA1h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonA1h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonA1h.setText("")
        self.buttonA1h.setIconSize(QtCore.QSize(50, 3))
        self.buttonA1h.setObjectName("buttonA1h")
        self.gridLayout_2.addWidget(self.buttonA1h, 11, 2, 1, 1)
        self.buttonE4h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonE4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonE4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonE4h.setText("")
        self.buttonE4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonE4h.setObjectName("buttonE4h")
        self.gridLayout_2.addWidget(self.buttonE4h, 5, 10, 1, 1)
        self.buttonB1v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB1v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB1v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB1v.setText("")
        self.buttonB1v.setObjectName("buttonB1v")
        self.gridLayout_2.addWidget(self.buttonB1v, 10, 3, 1, 1)
        self.buttonB6h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB6h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB6h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB6h.setText("")
        self.buttonB6h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB6h.setObjectName("buttonB6h")
        self.gridLayout_2.addWidget(self.buttonB6h, 1, 4, 1, 1)
        self.label5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label5.setObjectName("label5")
        self.gridLayout_2.addWidget(self.label5, 2, 0, 2, 1)
        self.buttonC4h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonC4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonC4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonC4h.setText("")
        self.buttonC4h.setObjectName("buttonC4h")
        self.gridLayout_2.addWidget(self.buttonC4h, 5, 6, 1, 1)
        self.buttonB3v = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB3v.setMinimumSize(QtCore.QSize(10, 80))
        self.buttonB3v.setMaximumSize(QtCore.QSize(10, 80))
        self.buttonB3v.setText("")
        self.buttonB3v.setObjectName("buttonB3v")
        self.gridLayout_2.addWidget(self.buttonB3v, 6, 3, 1, 1)
        self.buttonB4h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB4h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB4h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB4h.setText("")
        self.buttonB4h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB4h.setObjectName("buttonB4h")
        self.gridLayout_2.addWidget(self.buttonB4h, 5, 4, 1, 1)
        self.labelB = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelB.setFont(font)
        self.labelB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelB.setObjectName("labelB")
        self.gridLayout_2.addWidget(self.labelB, 12, 3, 1, 2)
        self.buttonB5h = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.buttonB5h.setMinimumSize(QtCore.QSize(80, 10))
        self.buttonB5h.setMaximumSize(QtCore.QSize(80, 10))
        self.buttonB5h.setText("")
        self.buttonB5h.setIconSize(QtCore.QSize(50, 3))
        self.buttonB5h.setObjectName("buttonB5h")
        self.gridLayout_2.addWidget(self.buttonB5h, 3, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 11)
        self.labelF = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelF.setFont(font)
        self.labelF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelF.setObjectName("labelF")
        self.gridLayout_2.addWidget(self.labelF, 12, 11, 1, 2)
        self.label2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 8, 0, 2, 1)
        self.labelE = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelE.setFont(font)
        self.labelE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelE.setObjectName("labelE")
        self.gridLayout_2.addWidget(self.labelE, 12, 9, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(25, 30))
        self.label_13.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setIndent(20)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setMinimumSize(QtCore.QSize(25, 30))
        self.label_14.setMaximumSize(QtCore.QSize(25, 30))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setIndent(20)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 3, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(40, 25))
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(40, 25))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_3.addWidget(self.lcdNumber_2, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setMinimumSize(QtCore.QSize(0, 35))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 1, 1, 4)
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(40, 25))
        self.lcdNumber.setMaximumSize(QtCore.QSize(40, 25))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_3.addWidget(self.lcdNumber, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 5, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 0, 2, 1)
        self.currentStepTextLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentStepTextLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentStepTextLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.currentStepTextLabel.setFont(font)
        self.currentStepTextLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentStepTextLabel.setObjectName("currentStepTextLabel")
        self.gridLayout_3.addWidget(self.currentStepTextLabel, 1, 0, 1, 3)
        self.currentPlayerTextLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentPlayerTextLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentPlayerTextLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.currentPlayerTextLabel.setFont(font)
        self.currentPlayerTextLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentPlayerTextLabel.setObjectName("currentPlayerTextLabel")
        self.gridLayout_3.addWidget(self.currentPlayerTextLabel, 0, 0, 1, 3)
        self.currentStepLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentStepLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentStepLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.currentStepLabel.setFont(font)
        self.currentStepLabel.setObjectName("currentStepLabel")
        self.gridLayout_3.addWidget(self.currentStepLabel, 1, 3, 1, 3)
        self.currentPlayerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.currentPlayerLabel.setMinimumSize(QtCore.QSize(0, 35))
        self.currentPlayerLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setKerning(False)
        self.currentPlayerLabel.setFont(font)
        self.currentPlayerLabel.setAutoFillBackground(False)
        self.currentPlayerLabel.setIndent(35)
        self.currentPlayerLabel.setObjectName("currentPlayerLabel")
        self.gridLayout_3.addWidget(self.currentPlayerLabel, 0, 3, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.tableView = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 31))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label6.setText(_translate("MainWindow", "6"))
        self.label1.setText(_translate("MainWindow", "1"))
        self.labelD.setText(_translate("MainWindow", "D"))
        self.labelA.setText(_translate("MainWindow", "A"))
        self.label4.setText(_translate("MainWindow", "4"))
        self.label3.setText(_translate("MainWindow", "3"))
        self.labelC.setText(_translate("MainWindow", "C"))
        self.label5.setText(_translate("MainWindow", "5"))
        self.labelB.setText(_translate("MainWindow", "B"))
        self.labelF.setText(_translate("MainWindow", "F"))
        self.label2.setText(_translate("MainWindow", "2"))
        self.labelE.setText(_translate("MainWindow", "E"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">•</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0055ff;\">•</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "比  分"))
        self.currentStepTextLabel.setText(_translate("MainWindow", "当前步数: "))
        self.currentPlayerTextLabel.setText(_translate("MainWindow", "当前玩家: "))
        self.currentStepLabel.setText(_translate("MainWindow", "0"))
        self.currentPlayerLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">•</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "历史: "))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action.setText(_translate("MainWindow", "新游戏"))
        self.action_2.setText(_translate("MainWindow", "载入游戏"))
        self.action_4.setText(_translate("MainWindow", "保存游戏"))
        self.action_5.setText(_translate("MainWindow", "导出标准棋谱"))
        self.action_6.setText(_translate("MainWindow", "悔棋"))
        self.action_7.setText(_translate("MainWindow", "恢复"))

